# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="DSMSL (DON'T SNATCH MA STUFF LICENSE)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="fancymenu" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="FancyMenu" #mandatory
# A text field displayed in the mod UI
authors="Keksuccino" #optional
credits="xllifi - Made a lot of great looking icons for context menus!"
logoFile="fancymenu_logo_128x128.png"
# The description text for the mod (multi line!) (#mandatory)
description='''Give your life a fancy touch. You deserve it.

COPYRIGHT:

> FancyMenu © Copyright 2020-2023 Keksuccino.
  FancyMenu is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
  See https://github.com/Keksuccino/FancyMenu/blob/master/LICENSE.md for more information about this license.

> Japng © Copyright A. Ellerton.
  Japng is licensed under Apache-2.0.'''

[[dependencies.fancymenu]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.6.1,)"
side="BOTH"

[[dependencies.fancymenu]]
modId="melody"
mandatory=true
ordering="NONE"
versionRange="[1.0.0,)"
side="CLIENT"

[[dependencies.fancymenu]]
modId="findme"
mandatory=false
ordering="AFTER"
versionRange="[1.0.0,)"
side="BOTH"

[[dependencies.fancymenu]]
modId="drippyloadingscreen"
mandatory=false
ordering="NONE"
versionRange="[2.2.0,)"
side="BOTH"

[[dependencies.fancymenu]]
modId="forge"
mandatory=true
versionRange="[45.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.fancymenu]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"