modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
clientSideOnly=false
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}" #optional
#If mod is present on server, only let users with same client-side mod version join
displayTest="MATCH_VERSION"
description='''Give your life a fancy touch. You deserve it.

COPYRIGHT:

> FancyMenu © Copyright 2020-2023 Keksuccino.
  FancyMenu is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
  See https://github.com/Keksuccino/FancyMenu/blob/master/LICENSE.md for more information about this license.'''

[[dependencies.${mod_id}]]
    modId="konkrete"
    mandatory=true
    ordering="NONE"
    versionRange="[1.6.1,)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="findme"
    mandatory=false
    ordering="AFTER"
    versionRange="[1.0.0,)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="drippyloadingscreen"
    mandatory=false
    ordering="NONE"
    versionRange="[2.2.3,3.0.0)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
